version: '3.8'
services:
  backend:
    image: ghcr.io/ranger-ross/yakman-backend:0.0.3-alpha
    environment:
      - RUST_LOG=info
      - YAKMAN_ADAPTER=IN_MEMORY
      - YAKMAN_HOST=0.0.0.0
      - YAKMAN_PORT=8000

      - YAKMAN_DEFAULT_ADMIN_USER_EMAIL=test@null.com
      - YAKMAN_DEFAULT_ADMIN_USER_PASSWORD=YakMaster123

      - YAKMAN_ACCESS_TOKEN_SIGNING_KEY=12345
      - YAKMAN_REFRESH_TOKEN_ENCRYPTION_KEY=a secret key12345678123456781231
    ports:
      - "8000:8000"
  frontend:
    image: ghcr.io/ranger-ross/yakman-frontend:0.0.3-alpha
    environment:
      - YAKMAN_API_URL=http://backend:8000
      - ORIGIN=http://localhost:3000
    ports:
      - "3000:3000"

