name: Rust Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Cdebuginfo=2 -Cstrip=none --cfg=tarpaulin -Clink-dead-code"

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - run: rustup toolchain install stable --profile minimal --no-self-update

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: backend

    - run: cargo install cargo-tarpaulin
      working-directory: backend

    - run: cargo fmt --check
      working-directory: backend

    - run: cargo clippy -- -D warnings
      working-directory: backend

    - run: cargo tarpaulin --skip-clean --out xml
      working-directory: backend

    - name: Produce the coverage report
      uses: insightsengineering/coverage-action@v2
      with:
        path: backend/cobertura.xml
        publish: true
        diff: true
        diff-branch: main
